# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: debian-snapshot-cache
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: 80
    name: default
  selector:
    app: debian-snapshot-cache