# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: webhook-dispatcher-svc
  labels:
    app: webhook-dispatcher
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.webhook_dispatcher_port }}
    name: default
  selector:
    app: webhook-dispatcher
